OBJS = Engine/*.cpp
CC = g++
COMPILER_FLAGS = -w
LINKER_FLAGS = -lsfml-graphics -lsfml-system -lsfml-window -lsfml-network -lsfml-audio -lglfw3 -lglew32
OBJ_NAME = build/app

all : $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)