# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kacper/Pulpit/Projects/Voxeler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kacper/Pulpit/Projects/Voxeler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacper/Pulpit/Projects/Voxeler/CMakeFiles /home/kacper/Pulpit/Projects/Voxeler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacper/Pulpit/Projects/Voxeler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Voxeler

# Build rule for target.
Voxeler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Voxeler
.PHONY : Voxeler

# fast build rule for target.
Voxeler/fast:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/build
.PHONY : Voxeler/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) -f thirdparty/glad/CMakeFiles/glad.dir/build.make thirdparty/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) -f thirdparty/glad/CMakeFiles/glad-generate-files.dir/build.make thirdparty/glad/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f thirdparty/glfw/CMakeFiles/uninstall.dir/build.make thirdparty/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f thirdparty/glfw/src/CMakeFiles/glfw.dir/build.make thirdparty/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f thirdparty/glfw/docs/CMakeFiles/docs.dir/build.make thirdparty/glfw/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

Engine/App.o: Engine/App.cpp.o

.PHONY : Engine/App.o

# target to build an object file
Engine/App.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/App.cpp.o
.PHONY : Engine/App.cpp.o

Engine/App.i: Engine/App.cpp.i

.PHONY : Engine/App.i

# target to preprocess a source file
Engine/App.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/App.cpp.i
.PHONY : Engine/App.cpp.i

Engine/App.s: Engine/App.cpp.s

.PHONY : Engine/App.s

# target to generate assembly for a file
Engine/App.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/App.cpp.s
.PHONY : Engine/App.cpp.s

Engine/Core.o: Engine/Core.cpp.o

.PHONY : Engine/Core.o

# target to build an object file
Engine/Core.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core.cpp.o
.PHONY : Engine/Core.cpp.o

Engine/Core.i: Engine/Core.cpp.i

.PHONY : Engine/Core.i

# target to preprocess a source file
Engine/Core.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core.cpp.i
.PHONY : Engine/Core.cpp.i

Engine/Core.s: Engine/Core.cpp.s

.PHONY : Engine/Core.s

# target to generate assembly for a file
Engine/Core.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core.cpp.s
.PHONY : Engine/Core.cpp.s

Engine/Core/Math.o: Engine/Core/Math.cpp.o

.PHONY : Engine/Core/Math.o

# target to build an object file
Engine/Core/Math.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Math.cpp.o
.PHONY : Engine/Core/Math.cpp.o

Engine/Core/Math.i: Engine/Core/Math.cpp.i

.PHONY : Engine/Core/Math.i

# target to preprocess a source file
Engine/Core/Math.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Math.cpp.i
.PHONY : Engine/Core/Math.cpp.i

Engine/Core/Math.s: Engine/Core/Math.cpp.s

.PHONY : Engine/Core/Math.s

# target to generate assembly for a file
Engine/Core/Math.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Math.cpp.s
.PHONY : Engine/Core/Math.cpp.s

Engine/Core/Timer.o: Engine/Core/Timer.cpp.o

.PHONY : Engine/Core/Timer.o

# target to build an object file
Engine/Core/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Timer.cpp.o
.PHONY : Engine/Core/Timer.cpp.o

Engine/Core/Timer.i: Engine/Core/Timer.cpp.i

.PHONY : Engine/Core/Timer.i

# target to preprocess a source file
Engine/Core/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Timer.cpp.i
.PHONY : Engine/Core/Timer.cpp.i

Engine/Core/Timer.s: Engine/Core/Timer.cpp.s

.PHONY : Engine/Core/Timer.s

# target to generate assembly for a file
Engine/Core/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Timer.cpp.s
.PHONY : Engine/Core/Timer.cpp.s

Engine/Core/Window.o: Engine/Core/Window.cpp.o

.PHONY : Engine/Core/Window.o

# target to build an object file
Engine/Core/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Window.cpp.o
.PHONY : Engine/Core/Window.cpp.o

Engine/Core/Window.i: Engine/Core/Window.cpp.i

.PHONY : Engine/Core/Window.i

# target to preprocess a source file
Engine/Core/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Window.cpp.i
.PHONY : Engine/Core/Window.cpp.i

Engine/Core/Window.s: Engine/Core/Window.cpp.s

.PHONY : Engine/Core/Window.s

# target to generate assembly for a file
Engine/Core/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Core/Window.cpp.s
.PHONY : Engine/Core/Window.cpp.s

Engine/Game/game.o: Engine/Game/game.cpp.o

.PHONY : Engine/Game/game.o

# target to build an object file
Engine/Game/game.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/game.cpp.o
.PHONY : Engine/Game/game.cpp.o

Engine/Game/game.i: Engine/Game/game.cpp.i

.PHONY : Engine/Game/game.i

# target to preprocess a source file
Engine/Game/game.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/game.cpp.i
.PHONY : Engine/Game/game.cpp.i

Engine/Game/game.s: Engine/Game/game.cpp.s

.PHONY : Engine/Game/game.s

# target to generate assembly for a file
Engine/Game/game.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/game.cpp.s
.PHONY : Engine/Game/game.cpp.s

Engine/Game/player.o: Engine/Game/player.cpp.o

.PHONY : Engine/Game/player.o

# target to build an object file
Engine/Game/player.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/player.cpp.o
.PHONY : Engine/Game/player.cpp.o

Engine/Game/player.i: Engine/Game/player.cpp.i

.PHONY : Engine/Game/player.i

# target to preprocess a source file
Engine/Game/player.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/player.cpp.i
.PHONY : Engine/Game/player.cpp.i

Engine/Game/player.s: Engine/Game/player.cpp.s

.PHONY : Engine/Game/player.s

# target to generate assembly for a file
Engine/Game/player.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Game/player.cpp.s
.PHONY : Engine/Game/player.cpp.s

Engine/Inputs/Keyboard.o: Engine/Inputs/Keyboard.cpp.o

.PHONY : Engine/Inputs/Keyboard.o

# target to build an object file
Engine/Inputs/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Inputs/Keyboard.cpp.o
.PHONY : Engine/Inputs/Keyboard.cpp.o

Engine/Inputs/Keyboard.i: Engine/Inputs/Keyboard.cpp.i

.PHONY : Engine/Inputs/Keyboard.i

# target to preprocess a source file
Engine/Inputs/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Inputs/Keyboard.cpp.i
.PHONY : Engine/Inputs/Keyboard.cpp.i

Engine/Inputs/Keyboard.s: Engine/Inputs/Keyboard.cpp.s

.PHONY : Engine/Inputs/Keyboard.s

# target to generate assembly for a file
Engine/Inputs/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Inputs/Keyboard.cpp.s
.PHONY : Engine/Inputs/Keyboard.cpp.s

Engine/Network/Client.o: Engine/Network/Client.cpp.o

.PHONY : Engine/Network/Client.o

# target to build an object file
Engine/Network/Client.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Client.cpp.o
.PHONY : Engine/Network/Client.cpp.o

Engine/Network/Client.i: Engine/Network/Client.cpp.i

.PHONY : Engine/Network/Client.i

# target to preprocess a source file
Engine/Network/Client.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Client.cpp.i
.PHONY : Engine/Network/Client.cpp.i

Engine/Network/Client.s: Engine/Network/Client.cpp.s

.PHONY : Engine/Network/Client.s

# target to generate assembly for a file
Engine/Network/Client.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Client.cpp.s
.PHONY : Engine/Network/Client.cpp.s

Engine/Network/Network.o: Engine/Network/Network.cpp.o

.PHONY : Engine/Network/Network.o

# target to build an object file
Engine/Network/Network.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Network.cpp.o
.PHONY : Engine/Network/Network.cpp.o

Engine/Network/Network.i: Engine/Network/Network.cpp.i

.PHONY : Engine/Network/Network.i

# target to preprocess a source file
Engine/Network/Network.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Network.cpp.i
.PHONY : Engine/Network/Network.cpp.i

Engine/Network/Network.s: Engine/Network/Network.cpp.s

.PHONY : Engine/Network/Network.s

# target to generate assembly for a file
Engine/Network/Network.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Network.cpp.s
.PHONY : Engine/Network/Network.cpp.s

Engine/Network/Server.o: Engine/Network/Server.cpp.o

.PHONY : Engine/Network/Server.o

# target to build an object file
Engine/Network/Server.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Server.cpp.o
.PHONY : Engine/Network/Server.cpp.o

Engine/Network/Server.i: Engine/Network/Server.cpp.i

.PHONY : Engine/Network/Server.i

# target to preprocess a source file
Engine/Network/Server.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Server.cpp.i
.PHONY : Engine/Network/Server.cpp.i

Engine/Network/Server.s: Engine/Network/Server.cpp.s

.PHONY : Engine/Network/Server.s

# target to generate assembly for a file
Engine/Network/Server.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Network/Server.cpp.s
.PHONY : Engine/Network/Server.cpp.s

Engine/Renderer/Renderer.o: Engine/Renderer/Renderer.cpp.o

.PHONY : Engine/Renderer/Renderer.o

# target to build an object file
Engine/Renderer/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Renderer.cpp.o
.PHONY : Engine/Renderer/Renderer.cpp.o

Engine/Renderer/Renderer.i: Engine/Renderer/Renderer.cpp.i

.PHONY : Engine/Renderer/Renderer.i

# target to preprocess a source file
Engine/Renderer/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Renderer.cpp.i
.PHONY : Engine/Renderer/Renderer.cpp.i

Engine/Renderer/Renderer.s: Engine/Renderer/Renderer.cpp.s

.PHONY : Engine/Renderer/Renderer.s

# target to generate assembly for a file
Engine/Renderer/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Renderer.cpp.s
.PHONY : Engine/Renderer/Renderer.cpp.s

Engine/Renderer/Shader.o: Engine/Renderer/Shader.cpp.o

.PHONY : Engine/Renderer/Shader.o

# target to build an object file
Engine/Renderer/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Shader.cpp.o
.PHONY : Engine/Renderer/Shader.cpp.o

Engine/Renderer/Shader.i: Engine/Renderer/Shader.cpp.i

.PHONY : Engine/Renderer/Shader.i

# target to preprocess a source file
Engine/Renderer/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Shader.cpp.i
.PHONY : Engine/Renderer/Shader.cpp.i

Engine/Renderer/Shader.s: Engine/Renderer/Shader.cpp.s

.PHONY : Engine/Renderer/Shader.s

# target to generate assembly for a file
Engine/Renderer/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/Engine/Renderer/Shader.cpp.s
.PHONY : Engine/Renderer/Shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Voxeler"
	@echo "... glad"
	@echo "... glad-generate-files"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... docs"
	@echo "... Engine/App.o"
	@echo "... Engine/App.i"
	@echo "... Engine/App.s"
	@echo "... Engine/Core.o"
	@echo "... Engine/Core.i"
	@echo "... Engine/Core.s"
	@echo "... Engine/Core/Math.o"
	@echo "... Engine/Core/Math.i"
	@echo "... Engine/Core/Math.s"
	@echo "... Engine/Core/Timer.o"
	@echo "... Engine/Core/Timer.i"
	@echo "... Engine/Core/Timer.s"
	@echo "... Engine/Core/Window.o"
	@echo "... Engine/Core/Window.i"
	@echo "... Engine/Core/Window.s"
	@echo "... Engine/Game/game.o"
	@echo "... Engine/Game/game.i"
	@echo "... Engine/Game/game.s"
	@echo "... Engine/Game/player.o"
	@echo "... Engine/Game/player.i"
	@echo "... Engine/Game/player.s"
	@echo "... Engine/Inputs/Keyboard.o"
	@echo "... Engine/Inputs/Keyboard.i"
	@echo "... Engine/Inputs/Keyboard.s"
	@echo "... Engine/Network/Client.o"
	@echo "... Engine/Network/Client.i"
	@echo "... Engine/Network/Client.s"
	@echo "... Engine/Network/Network.o"
	@echo "... Engine/Network/Network.i"
	@echo "... Engine/Network/Network.s"
	@echo "... Engine/Network/Server.o"
	@echo "... Engine/Network/Server.i"
	@echo "... Engine/Network/Server.s"
	@echo "... Engine/Renderer/Renderer.o"
	@echo "... Engine/Renderer/Renderer.i"
	@echo "... Engine/Renderer/Renderer.s"
	@echo "... Engine/Renderer/Shader.o"
	@echo "... Engine/Renderer/Shader.i"
	@echo "... Engine/Renderer/Shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

